
modLoader="javafml"

loaderVersion="[31,)"

# issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="fractal"

version="1.15.2-1.0.0"

displayName="Fractal"

# updateJSONURL="http://myurl.me/"

# displayURL="http://example.com/"

logoFile="fractal_logo.png" #optional

credits="Thanks to [insert youtube tutorial(s) here]"

authors="Lerrific as main developer, Orbic as useless, Kamauu as useless, Steve as useless"

description='''

cool mod 123

'''


[[dependencies.fractal]]

    modId="forge"

    mandatory=true

    versionRange="[31,)"

    ordering="NONE"

    side="BOTH"

[[dependencies.fractal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
